---
title: Rolando Murillo
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: rolando@bandd.co
description: Product Designer And Engineer Based in New York City
baseurl: ''
url: http://rolandomurillo.com
markdown: kramdown
