# Site settings
title: Rolando Murillo
email: rolando@bandd.co
description: "Creating delightful & effective digital experiences"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rolandomurillo.com" # the base hostname & protocol for your site
twitter_username: rnmp
github_username:  rnmp

# Build settings
markdown: kramdown
