---
title: Rolando Murillo
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: rolando@bandd.co
description: Creating delightful & effective digital experiences
baseurl: ''
url: http://rolandomurillo.com
twitter_username: rnmp
github_username: rnmp
markdown: kramdown
