---
title: Rolando Murillo
timezone: UTC
collections:
  posts:
    title: Posts
    layout: post
    permalink: /:categories/:year/:month/:day/:title
    output: true
  projects:
    title: Projects
    layout: post
    output: true
  photos:
    output: true
defaults:
  - scope:
      path: ""
      type: photos
    values:
      layout: photo
  - scope:
      path: ""
      type: posts
    values:
      layout: post
email: rolandomurillo@hey.com
description: Digital Builder Based in New York City
baseurl: ''
url: https://rolandomurillo.com
markdown: kramdown
