---
title: Rolando Murillo
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: rolandomurillo@hey.com
description: Product Designer and Engineer Based in New York City
baseurl: ''
url: https://rolandomurillo.com
markdown: kramdown
